// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcczwfzdvnmqiuikjrlk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjY3p3Znpkdm5tcWl1aWtqcmxrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2MDU5MjUsImV4cCI6MjA1ODE4MTkyNX0.7-3KpL4OIioHBQ8cmY5kSiJ924PsK7yenVVm4Jk0Two";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);